# Generated by Django 5.2.8 on 2025-11-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountprofile_subscriptionplan_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('customer', 'Customer'), ('delivery', 'Delivery'), ('cse', 'Cse'), ('sm', 'Sm')], max_length=20),
        ),
    ]
