# Generated by Django 5.2.8 on 2025-11-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_subscriptionplan_accountprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('customer', 'Customer'), ('delivery', 'Delivery Person'), ('cse', 'Customer Service Executive'), ('sm', 'Subscription Manager')], max_length=20),
        ),
    ]
